import type { Space, SpaceType } from "./types";
import rawBoardConfig from "./board.config.json";

export const TOKENS = ["♠", "♥", "♦", "♣", "★", "◆", "●", "▲"];
export const COLORS = [
  "#36e0ff",
  "#ff5a8a",
  "#b06bff",
  "#2bd9a0",
  "#ffb84d",
  "#5a8cff",
];
export const MAX_PLAYERS = 6;
export const MIN_PLAYERS = 2;

/** Rent multiplier by building level (index 0 = unimproved, 5 = hotel). */
export const RENT_MULT = [1, 2, 3, 4, 5, 8];

/** Total number of spaces a valid board must define. Mirrors BOARD_SIZE in
 *  constants.ts; kept local to avoid an import cycle (constants reads the same
 *  config file for STARTING_CASH). */
const EXPECTED_SPACES = 40;

/** All allowed space kinds, used to validate the editable board config. */
const SPACE_TYPES: SpaceType[] = [
  "go", "prop", "rail", "util", "tax", "chance", "chest", "jail", "parking", "gotojail",
];

// Authentic Monopoly property-group colors. These are the eight built-in groups
// the default board ships with; the board editor may recolor them, in which case
// houseCost() falls back to a price-tier estimate (see HOUSE_COST_BY_COLOR).
const GROUP_COLOR = {
  brown: "#955436",
  lblue: "#aae0fa",
  pink: "#d93a96",
  orange: "#f7941d",
  red: "#ed1b24",
  yellow: "#fef200",
  green: "#1fb25a",
  blue: "#0072bb",
};

/** The editable board, as authored in game/board.config.json (and regenerated by
 *  the local /board-editor page). */
export interface BoardConfig {
  /** Cash every player starts the game with. */
  startingCash: number;
  /** The 40 board spaces, in board order (index == position). */
  spaces: Omit<Space, "idx" | "pos">[];
}

/**
 * Validate a board config so a malformed edit can never reach the running game.
 * Throws a descriptive Error on the first problem. Run at import time below (so a
 * bad committed config fails the build/tests) and by the editor before saving.
 */
export function validateBoardConfig(config: unknown): asserts config is BoardConfig {
  const c = config as BoardConfig;
  if (!c || typeof c !== "object") throw new Error("Board config must be an object.");
  if (typeof c.startingCash !== "number" || !Number.isFinite(c.startingCash) || c.startingCash <= 0) {
    throw new Error("Board config: startingCash must be a positive number.");
  }
  if (!Array.isArray(c.spaces) || c.spaces.length !== EXPECTED_SPACES) {
    throw new Error(`Board config: spaces must be an array of exactly ${EXPECTED_SPACES} entries.`);
  }
  c.spaces.forEach((space, idx) => {
    if (!space || typeof space !== "object") throw new Error(`Space ${idx}: not an object.`);
    if (!SPACE_TYPES.includes(space.t)) throw new Error(`Space ${idx}: invalid type "${space.t}".`);
    if (typeof space.name !== "string" || space.name.length === 0) {
      throw new Error(`Space ${idx}: name must be a non-empty string.`);
    }
    for (const key of ["price", "rent"] as const) {
      const v = space[key];
      if (v !== undefined && (typeof v !== "number" || !Number.isFinite(v) || v < 0)) {
        throw new Error(`Space ${idx}: ${key} must be a non-negative number.`);
      }
    }
    if (space.t === "prop") {
      if (typeof space.c !== "string" || space.c.length === 0) {
        throw new Error(`Space ${idx} (${space.name}): a property must have a color.`);
      }
      if (typeof space.price !== "number" || space.price <= 0) {
        throw new Error(`Space ${idx} (${space.name}): a property must have a positive price.`);
      }
    }
  });
  // Special-tile placement the engine relies on (jail cell index, go-to-jail).
  if (c.spaces[0].t !== "go") throw new Error("Board config: space 0 must be GO.");
  if (c.spaces[10].t !== "jail") throw new Error("Board config: space 10 must be JAIL.");
  if (c.spaces[30].t !== "gotojail") throw new Error("Board config: space 30 must be GO TO JAIL.");
}

validateBoardConfig(rawBoardConfig);

export const BOARD_CONFIG: BoardConfig = rawBoardConfig;

const SPACE_BLUEPRINTS: Omit<Space, "idx" | "pos">[] = BOARD_CONFIG.spaces;

/** Map a board index (0..39) to its [row, col] on the 11x11 grid. */
function gridPositionOf(boardIndex: number): [number, number] {
  if (boardIndex === 0) return [11, 11];
  if (boardIndex < 10) return [11, 11 - boardIndex];
  if (boardIndex === 10) return [11, 1];
  if (boardIndex < 20) return [11 - (boardIndex - 10), 1];
  if (boardIndex === 20) return [1, 1];
  if (boardIndex < 30) return [1, 1 + (boardIndex - 20)];
  if (boardIndex === 30) return [1, 11];
  return [1 + (boardIndex - 30), 11];
}

export const BOARD: Space[] = SPACE_BLUEPRINTS.map((space, idx) => ({
  ...space,
  idx,
  pos: gridPositionOf(idx),
}));

export function spaceColor(spaceIndex: number): string {
  const space = BOARD[spaceIndex];
  if (space.t === "prop") return space.c!;
  if (space.t === "rail") return "#8fa3c8";
  if (space.t === "util") return "#38e0c0";
  return "#9fb4d8";
}

export const isOwnable = (spaceType: SpaceType | string): boolean =>
  spaceType === "prop" || spaceType === "rail" || spaceType === "util";

/** Cost to add one house/hotel for the eight built-in color groups (classic
 *  Monopoly scaling). The editor may introduce new/recolored groups not in this
 *  map; houseCost() then falls back to a price-tier estimate. */
const HOUSE_COST_BY_COLOR: Record<string, number> = {
  [GROUP_COLOR.brown]: 50,
  [GROUP_COLOR.lblue]: 50,
  [GROUP_COLOR.pink]: 100,
  [GROUP_COLOR.orange]: 100,
  [GROUP_COLOR.red]: 150,
  [GROUP_COLOR.yellow]: 150,
  [GROUP_COLOR.green]: 200,
  [GROUP_COLOR.blue]: 200,
};

/** Estimate a build cost from a property's price, matching the classic 50/100/
 *  150/200 tiers. Used only when a color isn't in HOUSE_COST_BY_COLOR (i.e. the
 *  board was recolored in the editor). Reproduces the built-in costs exactly. */
function houseCostFromPrice(price: number): number {
  if (price <= 120) return 50;
  if (price <= 200) return 100;
  if (price <= 280) return 150;
  return 200;
}

export function houseCost(spaceIndex: number): number {
  const space = BOARD[spaceIndex];
  if (space.t !== "prop") return 0;
  return HOUSE_COST_BY_COLOR[space.c!] ?? houseCostFromPrice(space.price ?? 0);
}

/** All board indices in the same color group as `spaceIndex` (properties only). */
export function colorGroup(spaceIndex: number): number[] {
  const space = BOARD[spaceIndex];
  if (space.t !== "prop") return [];
  return BOARD.filter((s) => s.t === "prop" && s.c === space.c).map((s) => s.idx);
}

/** Cash raised by mortgaging a property (half its price). */
export function mortgageValue(spaceIndex: number): number {
  return Math.floor((BOARD[spaceIndex].price || 0) / 2);
}

/** Cost to lift a mortgage: the mortgage value plus 10% interest. */
export function unmortgageCost(spaceIndex: number): number {
  return Math.ceil(mortgageValue(spaceIndex) * 1.1);
}

/** Cash refunded for selling one house/hotel back to the bank (half build cost). */
export function sellValue(spaceIndex: number): number {
  return Math.floor(houseCost(spaceIndex) / 2);
}

/** True when every space index in `group` is owned by `playerIndex`. */
export function ownsWholeGroup(
  group: number[],
  owners: Record<number, number>,
  playerIndex: number,
): boolean {
  return group.length > 0 && group.every((spaceIndex) => owners[spaceIndex] === playerIndex);
}
